# Generated by Django 3.0.5 on 2020-04-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('deckId', models.AutoField(primary_key=True, serialize=False)),
                ('authorUsername', models.CharField(max_length=150)),
                ('deckSlug', models.SlugField(max_length=150)),
            ],
        ),
    ]
