# Generated by Django 3.0.5 on 2020-04-05 13:08

from django.db import migrations
from faker import Faker

def create_data(apps, schema_editor):
    Presentation = apps.get_model('no_drf_api', 'Presentation')
    fake = Faker()
    for _ in range(10):
        Presentation.objects.get_or_create(authorUsername=fake.first_name(),
                                            deckSlug=fake.last_name_female())



class Migration(migrations.Migration):

    dependencies = [
        ('no_drf_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
